name: Test action

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build-without-version:
    name: Build without version
    runs-on: ubuntu-latest

    steps:
      # Checks-out repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Use the local action
      - name: Setup PlatformIO (without version)
        uses: ./
        
      # Check if pio command works
      - name: Check pio command
        run: pio --help
        
  build-with-version:
    name: Build with version
    runs-on: ubuntu-latest

    steps:
      # Checks-out repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Use the local action
      - name: Setup PlatformIO (with version)
        uses: ./
        with:
          platformio-version: "5.2.5"
        
      # Check if pio command works
      - name: Check pio command
        run: pio --help
        
